easy-beasy:
  functional-test:
    base-uri: 'http://localhost'
spring:
  flyway:
    locations: classpath:/db/migrations,classpath:/db/seeders
  datasource:
    url: jdbc:postgresql://localhost:5432/easybeasy
    username: postgres
    password: 123456
