version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2-jdk-node-browsers-legacy
    steps:
      - checkout
  deploy-integracao:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
        name: Deploy para o ambiente de integracao
        command: |
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_INTEGRATION_APP_NAME.git master
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test