version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2-jdk-node-browsers-legacy
        environment:
          spring_profiles_active: dev
      - image: circleci/postgres:11
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: easybeasy

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: gradle dependencies
      - run: gradle test functionalTest

  deploy_integracao:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_INTEGRATION_APP_NAME.git master 2>&1 >/dev/null | sed "s/$HEROKU_API_KEY/SECRET/g"
workflows:
  version: 2
  build_padrao:
    jobs:
      - build
      - deploy_integracao:
          requires:
            - build
          filters:
            branches:
              only: master